# Generated by Django 4.0.2 on 2022-04-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantooapi', '0004_alter_interesttag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
